# Generated by Django 5.0.6 on 2024-07-07 12:38

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='chaiVerity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateadded', models.DateTimeField(verbose_name=django.utils.timezone.now)),
                ('type', models.CharField(choices=[('C', 'Chai'), ('T', 'Tea'), ('G', 'Green Tea'), ('O', 'Oolong Tea'), ('B', 'Black Tea'), ('P', 'Pu-erh Tea'), ('S', 'Sencha'), ('J', 'Jasmine'), ('L', 'Lemongrass'), ('M', 'Matcha'), ('R', 'Rooibos'), ('K', 'Kopi Luwak'), ('W', 'White Tea'), ('X', 'Yirgacheffe'), ('Y', 'Yerba Mate'), ('Z', 'Zen Tea')], max_length=2)),
            ],
        ),
    ]
