# Generated by Django 5.0.6 on 2024-07-07 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chai', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chaiverity',
            name='image',
            field=models.ImageField(default='default_image.jpg', upload_to='chais/'),
        ),
        migrations.AddField(
            model_name='chaiverity',
            name='name',
            field=models.CharField(default='simple chai', max_length=100),
        ),
    ]
