# Generated by Django 5.0.6 on 2024-07-07 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chai', '0002_chaiverity_image_chaiverity_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='chaiverity',
            name='description',
            field=models.TextField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='chaiverity',
            name='price',
            field=models.IntegerField(default=50),
        ),
    ]
